### ISSUE TITLE
Editor use localStorage

### ISSUE THREAD

**Issue by mamamia5x** [mamamia5x/markdownpedia#13]
Allow the user to use the editor and have their markdown files saved.

**Comment by fleventy-5** [comment]
@mamamia5x  can I give this a try??

**Comment by fleventy-5** [comment]
![image](https://user-images.githubusercontent.com/78148524/106356765-15c4e900-6328-11eb-9ec8-a4e645fd494a.png)


I was able to add the download option but the file is saved as txt do you have any idea for saving as markdown

**Comment by fleventy-5** [comment]
![image](https://user-images.githubusercontent.com/78148524/106356948-232ea300-6329-11eb-9afd-92753dae1f67.png)
@mamamia5x I am able to save file as markdown. So can you please merge my pull request

**Comment by mamamia5x** [comment]
Yeah, go right ahead. I see that you've already created a pull request. I'm busy at the moment, but I'll review it soon. Thanks for helping
