### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by mamamia5x** [mamamia5x/markdownpedia#19]
Logo for Markdownpedia. Currently we are just using Markdown's logo
![image](https://user-images.githubusercontent.com/57536929/106211186-e7130b00-618d-11eb-88cc-0449d5771a73.png)

It would be nice to see a new logo, but I don't know what it'll look like. 
If you're doing this one, be creative.

**Comment by 4rtmelly** [comment]
Hi, I have an idea for this one and already created it, where can i send you the result ? :)

**Comment by mamamia5x** [comment]
You can just post it here if you'd like.

**Comment by 4rtmelly** [comment]
![Logo Markdown Pedia](https://user-images.githubusercontent.com/60700094/109557123-f4e2e580-7ad7-11eb-96cb-e3bcffa28615.png)

**Comment by mamamia5x** [comment]
It looks great, I'll use it for the new update, but it may take some time. Thanks ;)
