### ISSUE TITLE
Better CSS

### ISSUE THREAD

**Issue by mamamia5x** [mamamia5x/markdownpedia#2]
We need a better css for the pages.

**Comment by Aiwwa** [comment]
Hi ! I can help you with better css :)

**Comment by mamamia5x** [comment]
Oh sweet thanks! If you can update the css [here](https://github.com/mamamia5x/markdownpedia/blob/main/vital/public/style.css).  If you want to update the page, you can do that here https://github.com/mamamia5x/markdownpedia/blob/main/vital/template.html.

**Comment by Aiwwa** [comment]
I chech files and have couple more question - dont realy know what improvemnst do yuo need in css file. 
About page update - it should look something like wikipedia yes ?

**Comment by mamamia5x** [comment]
Yeah, but with the simple page design. I like the sidebar, of wikpedia, then have the page details within the page.

**Comment by mamamia5x** [comment]
If you have anyquestions just ask.

**Comment by mamamia5x** [comment]
Or a dark theme @Aiwwa

**Comment by mamamia5x** [comment]
@Aiwwa I'm going to close this issue, because our css is pretty solid. But, if you'd like to edit some CSS, check out issue #18. The CSS of the site has changed a bit, and it would be pretty nice to see some CSS.
