### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by code-reaper08** [mamamia5x/markdownpedia#23]
Hey @mamamia5x 

Would you please let me know of the license on which [markdownpedia](https://github.com/mamamia5x/markdownpedia) fits.
It would be useful for me in my another issue at here https://github.com/mamamia5x/markdownpedia/issues/3

Thanks in advance 👍

**Comment by mamamia5x** [comment]
MIT license, and thanks again for helping. Sorry for responding so late.

**Comment by code-reaper08** [comment]
> MIT license, and thanks again for helping. Sorry for responding so late.

No problem at all !
Will reach out to you ASAP with this [issue](https://github.com/mamamia5x/markdownpedia/issues/3) 👍✨
