### ISSUE TITLE
Readme and home needs to be better

### ISSUE THREAD

**Issue by mamamia5x** [mamamia5x/markdownpedia#3]

**Comment by code-reaper08** [comment]
Hey @mamamia5x  !
I am willing to clean up the Readme 😄 
Could you please assign it to me ?

**Comment by mamamia5x** [comment]
Sure thing, thanks for helping.

**Comment by code-reaper08** [comment]
> Sure thing, thanks for helping.

Thanks @mamamia5x 👍 
I will start my work today 😄

**Comment by code-reaper08** [comment]
Hey @mamamia5x 😃
Cleaned up the README and added additional document files.
Please look into [this PR](https://github.com/mamamia5x/markdownpedia/pull/24)

Have a nice day 😁✨
