### ISSUE TITLE
Fix Editor

### ISSUE THREAD

**Issue by mamamia5x** [mamamia5x/markdownpedia#32]
FIx the editor to have the text area take up half the screen, and then have it resizeable.

**Comment by 4rtmelly** [comment]
Can i work on this one ? :)

**Comment by mamamia5x** [comment]
Sure thing!

**Comment by 4rtmelly** [comment]
Is it fine ?
![screenEditor](https://user-images.githubusercontent.com/60700094/111241186-ec70cb80-85fc-11eb-83b1-263a795a695f.PNG)

**Comment by mamamia5x** [comment]
That is how it originally was. It works perfectly.

**Comment by 4rtmelly** [comment]
Oh, when I open the index.html in editor, the textarea was half size this one.  To get the result of the screen I just take off "style = "float:left; width: 47.5%;" from the div id="content". Do you want me to make a pull request for this ?

**Comment by mamamia5x** [comment]
Sure. I didn't know the solution was that simple lol.

**Comment by mamamia5x** [comment]
Closed with #34
