### ISSUE TITLE
Create a page template

### ISSUE THREAD

**Issue by mamamia5x** [mamamia5x/markdownpedia#9]
An easy template for people to add a new page to the site.

**Comment by AtharvaParkale** [comment]
I would like to work on this issue.
Tell me about the template you want.

**Comment by AtharvaParkale** [comment]
> An easy template for people to add a new page to the site.

I would like to work on this issue.
Tell me about the template you want.

**Comment by mamamia5x** [comment]
Sorry for responding so late @AtharvaParkale.
I would like the template to be a simple markdown file. It'll have a header with the title, information and sources at the bottom.

Ex:
# [Title]
Info
* 1
* 2
* 3
## Sources

But please add more info to it. Like describing what should be in different headers. But you can do anything you really want, there isn't a preferred way to make articles. I want to see what the people (you) make, and go on with it.

**Comment by AtharvaParkale** [comment]
> Sorry for responding so late @AtharvaParkale.
> I would like the template to be a simple markdown file. It'll have a header with the title, information and sources at the bottom.
> 
> Ex:
> 
> # [Title]
> Info
> 
> * 1
> * 2
> * 3
> 
> ## Sources
> But please add more info to it. Like describing what should be in different headers. But you can do anything you really want, there isn't a preferred way to make articles. I want to see what the people (you) make, and go on with it.

Working on it!

**Comment by mamamia5x** [comment]
Thanks so much!

**Comment by AtharvaParkale** [comment]
> Thanks so much!

I have created an HTML template
Cant push,
It is showing some permissions required.

**Comment by AtharvaParkale** [comment]
> Thanks so much!

Permission denied.
Please allow permissions.

**Comment by mamamia5x** [comment]
Can you create a pull request?

**Comment by mamamia5x** [comment]
Or fork the project and push to your forked project, then create a pull request.

**Comment by AtharvaParkale** [comment]
> Or fork the project and push to your forked project, then create a pull request.

Done
